services:

  # ── KEYCLOAK ──────────────────────────────────────────────────────────────
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: bw-keycloak
    command: start-dev --import-realm
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
    volumes:
      - ./keycloak/buywise-realm.json:/opt/keycloak/data/import/buywise-realm.json
    depends_on:
      - keycloak-db
    networks:
      - bw-net

  # ── KEYCLOAK DB ───────────────────────────────────────────────────────────
  keycloak-db:
    image: postgres:16-alpine
    container_name: bw-keycloak-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - bw-net

  # ── POSTGRESQL ────────────────────────────────────────────────────────────
  postgres:
    image: postgres:16-alpine
    container_name: bw-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= 12345678
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./api/src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bw-net

  # ── REDIS ─────────────────────────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    container_name: bw-redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - bw-net

volumes:
  postgres-data:
  redis-data:
  ml-models:
  keycloak-db-data:

networks:
  bw-net:
    driver: bridge
  microservices-net:
    driver: bridge