server:
  port: 8080

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/kubo-realm

  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4321"
            allowedMethods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
            allowedHeaders: [ "*" ]
            allowCredentials: true

      webflux:
        environment:

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: product
          uri: 'http://localhost:9091'
          predicates:
            - Path=/api/products/**
          filters:
            - AddRequestHeader=X-Internal-Source, gateway

        - id: search
          uri: 'http://localhost:9092'
          predicates:
            - Path=/api/search, /api/search/**
          filters:
            - name: CircuitBreaker
              args:
                name: search-cb
                fallbackUri: forward:/fallback/search

        - id: purchase
          uri: 'http://localhost:9093'
          predicates:
            - Path=/api/purchase/**

        - id: kubo-fastapi
          uri: 'http://localhost:8000'
          predicates:
            - Path=/api/v1/scraping/**, /api/v1/ml/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: true

resilience4j:
  circuitbreaker:
    instances:
      search-cb:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.kubo.gateway: DEBUG