server:
  port: 8080

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          # Keycloak emite tokens con este issuer — el Gateway valida contra él
          issuer-uri: http://localhost:8180/realms/kubo-realm
          # Endpoint donde Keycloak publica sus claves públicas para verificar JWTs
          jwk-set-uri: http://localhost:8180/realms/kubo-realm/protocol/openid-connect/certs

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # CORS global — el Gateway lo maneja para todos los servicios
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"   # Frontend React dev
              - "http://localhost:5173"   # Vite dev server
            allowed-methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
            allowed-headers: ["*"]
            allow-credentials: true

      routes:
        - id: product
          uri: 'http://localhost:9091'
          predicates:
            - Path=/api/products/**  #Sin filtro de auth — endpoint público del plan freemium
          filters:
            - AddRequestHeader=X-Internal-Source, gateway


        - id: search
          uri: 'http://localhost:9092'
          predicates:
            - Path=/api/search/**
          filters:
            - name: JwtAuthFilter
            - name: CircuitBreaker
              args:
                name: search-cb
                fallbackUri: forward:/fallback/search


        - id: purchase
          uri: 'http://localhost:9092'
          predicates:
            - Path=/api/purchase/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: true

resilience4j:
  circuitbreaker:
    instances:
      search-cb:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.kubo.gateway: DEBUG